\c restaurant_reservations;
DROP TABLE IF EXISTS "date_hours" CASCADE;
DROP TABLE IF EXISTS "reservation" CASCADE;
DROP TABLE IF EXISTS "restaurant_table" CASCADE;
DROP SEQUENCE IF EXISTS "date_hours_seq";
DROP SEQUENCE IF EXISTS "restaurant_table_seq";
DROP SEQUENCE IF EXISTS "reservation_seq";

CREATE SEQUENCE date_hours_seq START 1;
CREATE SEQUENCE restaurant_table_seq START 1;
CREATE SEQUENCE reservation_seq START 1;

CREATE TABLE date_hours (
  ID SMALLINT PRIMARY KEY DEFAULT NEXTVAL('date_hours_seq'),
  START_HOUR SMALLINT NOT NULL,
  END_HOUR SMALLINT NOT NULL
);

CREATE TABLE restaurant_table (
  ID SMALLINT PRIMARY KEY DEFAULT NEXTVAL('restaurant_table_seq'),
  CAPACITY SMALLINT NOT NULL
);

CREATE TABLE reservation (
  ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('reservation_seq'),
  RESTAURANT_TABLE_ID SMALLINT,
  START_TIME DATE NOT NULL,
  END_TIME DATE NOT NULL,
  FOREIGN KEY(RESTAURANT_TABLE_ID) REFERENCES RESTAURANT_TABLE(ID)
);

