\c restaurant_reservations;
DROP TABLE IF EXISTS "reservation" CASCADE;
DROP TABLE IF EXISTS "restaurant_table" CASCADE;
DROP TABLE IF EXISTS "guest" CASCADE;
DROP SEQUENCE IF EXISTS "reservation_seq";
DROP SEQUENCE IF EXISTS "restaurant_table_seq";
DROP SEQUENCE IF EXISTS "guest_seq";

CREATE SEQUENCE reservation_seq START 1;
CREATE SEQUENCE restaurant_table_seq START 1;
CREATE SEQUENCE guest_seq START 1;

CREATE TABLE restaurant_table (
  ID SMALLINT PRIMARY KEY DEFAULT NEXTVAL('restaurant_table_seq'),
  CAPACITY SMALLINT NOT NULL
);

CREATE TABLE guest (
  ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('guest_seq'),
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME VARCHAR NOT NULL,
  EMAIL_ADDRESS VARCHAR,
  PASSWORD VARCHAR,
  REGISTERED BOOLEAN NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE reservation (
  ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('reservation_seq'),
  RESTAURANT_TABLE_ID SMALLINT,
  GUEST_ID INTEGER,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  UPDATED_DATE TIMESTAMP NOT NULL,
  FOREIGN KEY(RESTAURANT_TABLE_ID) REFERENCES RESTAURANT_TABLE(ID),
  FOREIGN KEY(GUEST_ID) REFERENCES GUEST(ID)
);

